### ISSUE TITLE
扫描预览相机倒过来了，翻转了180°，求解决

### ISSUE THREAD

**Issue by ashuang520** [yuzhiqiang1993/zxing#100]
我这个设备 扫描预览这个相机是倒过来的，求解决啊？谢谢

**Comment by ashuang520** [comment]
手持设备，操作系统都是android 的，估计与厂商定制有关，能否解决？

**Comment by yuzhiqiang1993** [comment]
如果是只该设备用的，那只能试着改源码实现了

**Comment by ashuang520** [comment]
相机打开正常，没有倒转，集成这个扫描这个界面就倒转了

**Comment by yuzhiqiang1993** [comment]
我这边暂时还没有遇见翻转的问题，很可能就是厂商定制导致的，你试试其他的扫描app正常吗？
