### ISSUE TITLE
请教一下,有关内存泄漏。

### ISSUE THREAD

**Issue by LLYYKK** [yuzhiqiang1993/zxing#101]
我在一个Fragment的Adpter中
写了：((MainActivity)getContext()).startActivityForResult(intent, REQUEST_CODE_SCAN);
并且在MainActivity中重写了onActivityResult方法。扫码可以成功进行，但是内存泄漏工具leak一直不停地报告内存泄漏...所以想请教一下如何在Adapter中调用扫码功能而不会内存泄露呢？

**Comment by yuzhiqiang1993** [comment]
请问有详细的内存泄漏信息吗？

**Comment by shiqikai** [comment]
+1内存泄漏

**Comment by yuzhiqiang1993** [comment]
试试最新版本2.2.6

**Comment by shiqikai** [comment]
嗯 可以了 感谢维护精神 让我们得到便利

**Comment by yuzhiqiang1993** [comment]
感谢反馈
