### ISSUE TITLE
第一次识别速度有点太慢了，给十多秒

### ISSUE THREAD

**Issue by liuhang12138** [yuzhiqiang1993/zxing#109]
希望能改进一下，第一次识别的速度，以后打开都很快

**Comment by yuzhiqiang1993** [comment]
第一次很慢？我这边暂时还没遇见过这种问题....,请问demo有这个情况吗？

**Comment by liuhang12138** [comment]
demo昨天暂时没试，昨天直接看文档集成的，今天不忙的时候，我试一下demo

**Comment by liuhang12138** [comment]
我发现了，通过studio直接运行到手机上扫码测试，第一次扫的就很慢，把应用彻底关闭，再次打开，扫码就很快了

**Comment by liuhang12138** [comment]
集成这个项目，有需要混淆的地方吗

**Comment by yuzhiqiang1993** [comment]
不需要混淆的
