### ISSUE TITLE
导入失败啊，有dalao能来帮帮忙嘛，orz

### ISSUE THREAD

**Issue by GHOSTSED** [yuzhiqiang1993/zxing#111]

**Comment by yuzhiqiang1993** [comment]
按照文档一步步走啊大兄弟

**Comment by GHOSTSED** [comment]
请问只要在相应位置添加
maven { url 'https://jitpack.io' }
和
implementation 'com.github.yuzhiqiang1993:zxing:2.2.5'，
然后在Manifest.xml节点下添加<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.FLASHLIGHT" />
<uses-feature android:name="android.hardware.camera" />
<uses-feature android:name="android.hardware.camera.autofocus" />
<uses-permission android:name="android.permission.VIBRATE" />
<uses-permission android:name="android.permission.WAKE_LOCK" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

再在Oncreat方法里写
Intent intent = new Intent(MainActivity.this, CaptureActivity.class);
startActivityForResult(intent, REQUEST_CODE_SCAN);
就可以了吗。我这么操作下来运行的时候REQUEST_CODE_SCAN是红色的，提示无法识别
我中间难道操作错了吗，求告知OAO

**Comment by yuzhiqiang1993** [comment]
REQUEST_CODE_SCAN是当前页面的一个变量，你自己随便起名字声明一个就行

**Comment by GHOSTSED** [comment]
请问我把REQUEST_CODE_SCAN换成111之后，程序可以在虚拟机上运行，但是显示“相机被占用或没有权限”。是不是这两句话
Manifest.permission.CAMERA
Manifest.permission.READ_EXTERNAL_STORAGE
也要加到代码里面啊，求指教

**Comment by GHOSTSED** [comment]
是不是因为我的虚拟机是android 8.0的呢

**Comment by yuzhiqiang1993** [comment]
不是，你没有给权限，具体你看下demo的代码
