### ISSUE TITLE
Release build 报错

### ISSUE THREAD

**Issue by liupeng826** [yuzhiqiang1993/zxing#115]
Android studio 3.3.2
release build 的时候报一下错误
Android resource linking failed
error: resource style/Theme.AppCompat.Light.NoActionBar (aka com.yzq.zxinglibrary:style/Theme.AppCompat.Light.NoActionBar) not found.
/Users/v0cn123/Android/AndroidStudio/zxing/zxinglibrary/build/intermediates/res/merged/release/values/values.xml:24: error: style attribute 'attr/colorPrimary (aka com.yzq.zxinglibrary:attr/colorPrimary)' not found.
/Users/v0cn123/Android/AndroidStudio/zxing/zxinglibrary/build/intermediates/res/merged/release/values/values.xml:25: error: style attribute 'attr/colorPrimaryDark (aka com.yzq.zxinglibrary:attr/colorPrimaryDark)' not found.
/Users/v0cn123/Android/AndroidStudio/zxing/zxinglibrary/build/intermediates/res/merged/release/values/values.xml:26: error: style attribute 'attr/windowActionBar (aka com.yzq.zxinglibrary:attr/windowActionBar)' not found.
/Users/v0cn123/Android/AndroidStudio/zxing/zxinglibrary/build/intermediates/res/merged/release/values/values.xml:27: error: style attribute 'attr/windowNoTitle (aka com.yzq.zxinglibrary:attr/windowNoTitle)' not found.
error: failed linking references.

**Comment by yuzhiqiang1993** [comment]
请问是按照文档流程走的么

**Comment by liupeng826** [comment]
我是直接clone下来你这个工程，debug编译没问题，release编译不过

**Comment by yuzhiqiang1993** [comment]
检查一下本地的环境，清除缓存rebuild试一下

**Comment by liupeng826** [comment]
可能是AndroidX的问题，我改成AndroidX试一下
