### ISSUE TITLE
Fragment中无法收到回调

### ISSUE THREAD

**Issue by weishubaoforwork** [yuzhiqiang1993/zxing#118]
Viewpager+Fragemt中，在承载碎片的Activity中的回调无法得到，我猜你应该是去掉了IntentIntegrator有两个方法是forFragment和forSupportFragment的两个方法，或者请你告诉我如何Fragment得到这个SetResult。

**Comment by yuzhiqiang1993** [comment]
你的Activity有没有把启动模式设置为singleTask？

**Comment by weishubaoforwork** [comment]
已经将CaptureActivity设置为SingleTask，并且利用EVENTBUS去传递到Fragment，发现不论Activity或者Fragment依然没有办法得到扫描的返回值。

**Comment by yuzhiqiang1993** [comment]
我的意思是不要将Activity启动模式设置为SingleTask，否则会出现接收不到的情况

**Comment by weishubaoforwork** [comment]
`  Intent intent = new Intent(getActivity() ,CaptureActivity.class);
                        ZxingConfig config = new ZxingConfig();
                        config.setFullScreenScan(false);//是否全屏扫描  默认为true  设为false则只会在扫描框中扫描
                        intent.putExtra(Constant.INTENT_ZXING_CONFIG, config);
                        startActivityForResult(intent, 1111);`


在Activityresult中

` if (requestCode == 1111 && resultCode == RESULT_OK) {
            if (data != null) {
                String content = data.getStringExtra(Constant.CODED_CONTENT);
                Log.e("TAG",content);
                EventBus.getDefault().post(new QRCodeEvent(content));

            }`

**Comment by yuzhiqiang1993** [comment]
应该是你写的有问题，我刚试过了，没有问题的

**Comment by yuzhiqiang1993** [comment]
我把在Fragment中使用扫一扫的代码示例加上了，你可以把代码拉下来看一下

**Comment by weishubaoforwork** [comment]
我这边已经试过了，找到问题根源，不知道为什么我的RequestCode莫名其妙变成了6667，后期修改后完成可以收到了。感谢楼主

**Comment by yuzhiqiang1993** [comment]
不客气
