### ISSUE TITLE
我也是要自定义UI 所以导入了module 但是这些是什么东西？

### ISSUE THREAD

**Issue by iEccentric** [yuzhiqiang1993/zxing#12]
Information:Gradle tasks [:zxinglibrary:generateDebugSources, :zxinglibrary:generateDebugAndroidTestSources, :zxinglibrary:mockableAndroidJar, :app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar]

/Users/eccentric/Documents/android/MyZxing/zxinglibrary/build/intermediates/bundles/debug/res/layout/activity_capture.xml
Error:error: attribute 'com.yzq.zxinglibrary.test:srcCompat' not found.
Error:error: attribute 'com.yzq.zxinglibrary.test:srcCompat' not found.
Error:attribute 'com.yzq.zxinglibrary.test:srcCompat' not found.
Error:attribute 'com.yzq.zxinglibrary.test:srcCompat' not found.
Error:failed linking file resources.
Error:java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:Execution failed for task ':zxinglibrary:processDebugAndroidTestResources'.
> Failed to execute aapt

**Comment by yuzhiqiang1993** [comment]
你好，2.1.0版本已修复，给你带来的不便表示歉意

**Comment by iEccentric** [comment]
没有不便 后来我直接复制整个module到项目里了 如果你能封装好一个直接可以自定义布局就好了 你可以看看这个人的https://github.com/yipianfengye/android-zxingLibrary    我本来是用他的 但是识别太慢了 所以我还是用了你的项目 还是得感谢你
