### ISSUE TITLE
2.2.7版本中文 app_name 被覆盖

### ISSUE THREAD

**Issue by 13568810905** [yuzhiqiang1993/zxing#121]
更新到2.2.7后发现zh资源文件中残留了
```xml
<string name="app_name">Zxing Library</string>
```
如果APP多语言默认values值为中文，没有专门配置中文资源文件的话，在中文环境下`Zxing Library`会覆盖掉软件名称  

![image](https://user-images.githubusercontent.com/34223095/55213930-ed519c80-522f-11e9-83a1-05cae0d2589b.png)

**Comment by yuzhiqiang1993** [comment]
嗯  我也发现了，感谢反馈，下个版本修改，建议你这边自己的项目先暂时将app_name修改一下，然后在清单配置文件应用修改过后的名字。

**Comment by 13568810905** [comment]
嗯 我现在就是直接创建了个中文的配置文件

**Comment by yuzhiqiang1993** [comment]
好的，再次感谢反馈
