### ISSUE TITLE
发布版和测试版的区别

### ISSUE THREAD

**Issue by ZhangPeng0220** [yuzhiqiang1993/zxing#122]
我发现一个问题，我直接用AS运行你的代码，出来的应用。和你二维码发布的应用识别速度差了一些，你的发布版明显比代码版要快。请问你是优化了哪里呢

**Comment by yuzhiqiang1993** [comment]
实际上他们的代码是完全一模一样的，flutter也有这个问题，debug的时候会有点卡，但是发布后就很流畅，我也搞不懂是为什么
