### ISSUE TITLE
急急急急

### ISSUE THREAD

**Issue by ZhangPeng0220** [yuzhiqiang1993/zxing#123]
大佬，我单独建立一个demo，集成你的代码是没啥问题的，但是我把东西放到公司项目上就扫描的特别慢，这种一般都是什么原因呢？？我应该从哪方面去排查问题呢

**Comment by yuzhiqiang1993** [comment]
这个我还真不知道是什么原因，我也很纳闷，我这边没有暂时还没有遇见过这种问题

**Comment by ZhangPeng0220** [comment]
有没有详细介绍，你的代码的博客，我想查一下原因，代码有的看不懂，没找到扫描，识别解码的入口

**Comment by yuzhiqiang1993** [comment]
https://yuzhiqiang.blog.csdn.net/article/details/52805057 看看这个，别的没有了
