### ISSUE TITLE
提两点界面的小建议

### ISSUE THREAD

**Issue by tempersitu** [yuzhiqiang1993/zxing#124]
刚好碰上作者更新了,十分感谢.用了有一段时间了.也本地化自己修改过.如果作者能加上自定义扫描页的action bar颜色,标题文字,返回按钮的icon和页面提示语句的位置(上或下足以), 那就更完美了.虽然可以继承这个activity后修改或者本地化之后修改,但会麻烦一点. 再次感谢作者的付出

**Comment by yuzhiqiang1993** [comment]
最近有点忙，后面有时间的话打算重构一版，把之前提出的问题着手解决一下，感谢建议

**Comment by tempersitu** [comment]
> 最近有点忙，后面有时间的话打算重构一版，把之前提出的问题着手解决一下，感谢建议

谢谢百忙之中回复.简单的在控件或layout上都加上id就已经方便一些的了.继承后修改也容易点. ^_^
