### ISSUE TITLE
想问一下这个对焦的原理

### ISSUE THREAD

**Issue by handsomeWaterMelon** [yuzhiqiang1993/zxing#126]
我发现当我把扫瞄取景框上移了，或者把view.ViewfinderView变成之前一半大，下面变成不透明，如变成红色。实别率就会下降，请问是为什么。 能否在不影响实别率的基础上，把扫瞄框向上移，并且扫瞄框下面变成不透明，放一些按钮什么的。

**Comment by handsomeWaterMelon** [comment]
。。。准确说不是实别率下降，而是难以对焦。。摄像头上的画面一直有些模糊，所以无法实别。或者比较慢。

**Comment by yuzhiqiang1993** [comment]
不知道你修改什么了，导致对焦慢，修改之前有这个问题吗

**Comment by handsomeWaterMelon** [comment]
修改之前是好的，我改了cameraManager里面，把实别的框上移，之前只改了public synchronized Rect getFramingRect() ，
int topOffset = (screenResolution.y - height) / 10;   之前是/5，现在改成/10了

发现好像还是不好实别，今天看了下发现setManualFramingRect里面好像也要一起改。。就好了，谢谢回复哈，这个项目做的很棒

**Comment by yuzhiqiang1993** [comment]
恩  对的  是要一起修改
