### ISSUE TITLE
5.1的手机全部crash

### ISSUE THREAD

**Issue by shuruncs** [yuzhiqiang1993/zxing#14]
A TaskDescription's primary color should be opaque！
我的primary color并没有设置透明，但是还是报这个错

**Comment by yuzhiqiang1993** [comment]
感谢反馈，我会测试解决的。

**Comment by yuzhiqiang1993** [comment]
你好，麻烦试一下2.0.4-dev版本，谢谢。      implementation 'com.github.yuzhiqiang1993:zxing:2.0.4-dev'

**Comment by shuruncs** [comment]
可以了，感谢！
