### ISSUE TITLE
使用FOCUS_MODE_AUTO无法在某些设备上准确对焦

### ISSUE THREAD

**Issue by aviraxp** [yuzhiqiang1993/zxing#144]
在其他使用API1的相机应用中使用FOCUS_MODE_AUTO可以正常对焦，但不知为何在原版zxing与本版本上均无法正常使用，看日志似乎是卡在对焦状态了，使用continuous-picture参数即可正常对焦。能否在这块做个处理，或者统一使用continuous-picture？（这个应该是兼容auto的）

**Comment by aviraxp** [comment]
zxing在若干年前留了个口子，我刚好改一下：https://github.com/zxing/zxing/pull/1186

**Comment by yuzhiqiang1993** [comment]
可以的，感谢您的建议

**Comment by aviraxp** [comment]
这个逻辑好像不对吧，FOCUS_MODES_CALLING_AF 这个Collection完全在之后没有引用，zxing的处理方式是直接根据是否使用auto模式调节useAutoFocus，这块的处理应该是要先setFocusMode(Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE)？

https://github.com/zxing/zxing/blob/0cf3b9be71680f50c90a71ca26ce0d33664b0dd6/android-core/src/main/java/com/google/zxing/client/android/camera/CameraConfigurationUtils.java#L55

**Comment by yuzhiqiang1993** [comment]
我想起来了，当时就是因为这个对焦有问题，最后使用的是一个异步任务不停的去对焦
