### ISSUE TITLE
依赖

### ISSUE THREAD

**Issue by Hacker1248084491** [yuzhiqiang1993/zxing#148]
ERROR: Failed to parse XML in C:\Users\HZHH\AndroidStudioProjects\STNACompanyApp\STNACompanyApp\app\src\main\AndroidManifest.xml
ParseError at [row,col]:[6,46]
Message: expected start or end tag
Affected Modules: app

老哥，按你说的依赖完出现这个问题

**Comment by yuzhiqiang1993** [comment]
看你提供的日志好像跟我的库没啥关系啊
