### ISSUE TITLE
androidX支持

### ISSUE THREAD

**Issue by luojianping168** [yuzhiqiang1993/zxing#165]
有没有支持androidx?

**Comment by yuzhiqiang1993** [comment]
你好，目前这个库后期有计划更新一个大版本，等待CameraX稳定后，到时候会用kotlin重写一遍，之前的bug和需求也都会着手是解决，AndroidX肯定会支持。

**Comment by yuzhiqiang1993** [comment]
抱歉这么久才更新 2.2.9版本已支持AndroidX
