### ISSUE TITLE
下载zxing.aar异常

### ISSUE THREAD

**Issue by hibadboy** [yuzhiqiang1993/zxing#173]
ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not download zxing.aar (com.github.yuzhiqiang1993:zxing:2.2.6)
换了好几个版本都下载失败

**Comment by yuzhiqiang1993** [comment]
看下文档，注意不要遗漏： maven { url 'https://jitpack.io' }

**Comment by hibadboy** [comment]
已解决，网络问题，公司网不知道为什么下载不了，会宿舍下载好了
