### ISSUE TITLE
自定义颜色

### ISSUE THREAD

**Issue by DreamClimb** [yuzhiqiang1993/zxing#24]
生成二维码的时候可以自定义二维码的颜色还有二维码的背景颜色，什么时候可以加上？还有就是自定义logo的？
扫描框的颜色，还有扫描线。

**Comment by yuzhiqiang1993** [comment]
不好意思，最近比较忙，后期有时间我会加上。

**Comment by yuzhiqiang1993** [comment]
2.1.8版本已更新
