### ISSUE TITLE
怎么把扫描结果传值

### ISSUE THREAD

**Issue by EvenYangyufan** [yuzhiqiang1993/zxing#27]
我把您的代码放在了一个framelayout里面，主界面是由底部导航栏，然后每一个导航按钮对应一个界面，我把扫一扫代码放在了其中一个public class **** extends Fragment（）{***}中，但是目前只能扫一扫并传回一个toast，如何进行扫一扫后，传到那个界面中的textview中显示出来呢？

**Comment by yuzhiqiang1993** [comment]
你好，你这个问题属于传值的问题了，传值有很多方式，广播，callback，Handler等都可以，建议你使用eventbus传递，比较方便。

**Comment by EvenYangyufan** [comment]
非常感谢！已经解决！
