### ISSUE TITLE
聚焦焦点显示不在取景框中

### ISSUE THREAD

**Issue by zhangxianpeng** [yuzhiqiang1993/zxing#28]
有没有发现黄色的点出现在取景框下方

**Comment by yuzhiqiang1993** [comment]
你好，咱这个扫描实际上是全屏扫描的，也就是说你不一定非要将扫描框对准二维码才能扫描，所以黄点也是在全屏范围内随机显示的

**Comment by zhangxianpeng** [comment]
但是我总觉得给用户的体验是一个比较不成熟的体验，所以我还是选择重写了那个View

**Comment by yuzhiqiang1993** [comment]
好的  这个你根据你的需求改一下就行了
