### ISSUE TITLE
集成进项目之后识别超级慢

### ISSUE THREAD

**Issue by Thinkingpey** [yuzhiqiang1993/zxing#3]
用例子中的apk扫描基本都是打开描扫，但是集成进自己的项目之后，要识别半天，一时找不到思路，想请教下。

**Comment by yuzhiqiang1993** [comment]
正常来说是不会有这种问题的啊

**Comment by ylcBaby** [comment]
大神，我也发现同样的问题，集成后扫描都是两秒才扫出结果，明显比你的apk扫描慢很多，而且不管是apk还是集成后的扫码都会出现长时间聚焦不了的bug，望大神能优化，谢了

**Comment by liguangze** [comment]
+1

**Comment by yuzhiqiang1993** [comment]
我自己也是直接按照文档的方法集成到我的项目中的，识别速度跟demo基本一致，聚焦这个问题可能跟设备有关系吧，有时间我看看到底怎么回事儿。

**Comment by liguangze** [comment]
E:\studioWorkspace\zxing-master\app\src\main\java\com\yzq\zxing\MainActivity.java
Error:(20, 24) 错误: 程序包com.google.zxing不存在
Error:(24, 33) 错误: 程序包com.yzq.zxinglibrary.bean不存在
Error:(25, 35) 错误: 程序包com.yzq.zxinglibrary.common不存在
Error:(26, 35) 错误: 程序包com.yzq.zxinglibrary.encode不存在
Error:(88, 33) 错误: 找不到符号
符号: 类 ZxingConfig
Error:(88, 58) 错误: 找不到符号
符号: 类 ZxingConfig
Error:(91, 49) 错误: 找不到符号
符号: 变量 Constant

studio改成了3.0以下的方式，这些都找不到呢，什么原因

**Comment by jdson** [comment]
哎 我也是遇到了这个问题   demo速度秒开  但是放到项目基本就识别不出来

**Comment by yuzhiqiang1993** [comment]
请问你是直接依赖使用的还是把源码moudle依赖进你的项目中使用的呢？

**Comment by yuzhiqiang1993** [comment]
http://blog.csdn.net/yuzhiqiang_1993/article/details/78292004  在博客下面的评论有人测试过，说是不删除build文件就不会出现这种问题，是不是你们作为moudle使用的时候修改了build文件，导致没有把zxing的jar包依赖进去。我这边直接依赖使用速度还是很快的。

**Comment by jdson** [comment]
我要定制ui界面 所以是添加的moudle 恩 我再试试 谢谢

**Comment by yuzhiqiang1993** [comment]
如果问题了解决了还请将解决方法分享一下，以便其他人参考，谢谢！

**Comment by yuzhiqiang1993** [comment]
2.1.0版本已更新，更新详情可查看更新日志[https://github.com/yuzhiqiang1993/zxing/wiki/update-log](https://github.com/yuzhiqiang1993/zxing/wiki/update-log)
