### ISSUE TITLE
REQUEST_CODE_SCAN

### ISSUE THREAD

**Issue by YangJuneva** [yuzhiqiang1993/zxing#34]
请问这个常量REQUEST_CODE_SCAN代表什么意思啊? 项目中没有这个常量啊

**Comment by yuzhiqiang1993** [comment]
你好  这个REQUEST_CODE_SCAN是自己定义的一个int类型的值，在
startActivityForResult(intent, REQUEST_CODE_SCAN);这一行代码会用到，这个变量名称可以随便改，跟平时使用startActivityForResult是一样的

**Comment by Geek-Z** [comment]
。原来如此
