### ISSUE TITLE
使用中的问题

### ISSUE THREAD

**Issue by oliverchu** [yuzhiqiang1993/zxing#35]
你好，我在使用过程中发现一些问题：
1.如果设置成非全屏扫描，那么将二维码成像在整个正方形框中，这个时候是识别不了的，必须有一定距离才会识别到。
2.设置setShowAlbum(true)后，发现会闪退。

机型：小米Note3 android 7.1.1 miui9开发版本
详细：1080P 屏幕

**Comment by yuzhiqiang1993** [comment]
1.全屏扫描速度确实会快一些，如果没有特殊需求建议就直接用全屏扫描
2.有详细的报错信息吗

**Comment by yuzhiqiang1993** [comment]
没有后续信息，故关闭
