### ISSUE TITLE
依赖

### ISSUE THREAD

**Issue by ganduwei** [yuzhiqiang1993/zxing#37]
你好，为何我添加依赖时使用2.1.4的版本：
 compile 'com.github.yuzhiqiang1993:zxing:2.1.4'
可以依赖成功但是使用2.1.8的版本就不成功：
compile 'com.github.yuzhiqiang1993:zxing:2.1.8'

**Comment by yuzhiqiang1993** [comment]
重新依赖一下试试，可能是缓存的原因，或者重新打开Studio
