### ISSUE TITLE
rv

### ISSUE THREAD

**Issue by yuanmaio** [yuzhiqiang1993/zxing#38]
我想问下，怎么改扫描框的大小

**Comment by yuanmaio** [comment]
我想问下，怎么改扫描框的大小

**Comment by yuzhiqiang1993** [comment]
后期有时间我提供个配置项，如果你急用的话可以下载源码直接在CameraManager这个类中改一下就好了

**Comment by yuzhiqiang1993** [comment]
ui上无法满足所有人的个性化需求，建议下载源码依赖后自行修改
