### ISSUE TITLE
关于引入重复依赖包请教一下

### ISSUE THREAD

**Issue by dzghxs** [yuzhiqiang1993/zxing#39]
大神，我想问一下，我现在项目中集成的一个打印的jar包中有了zxing，您的依赖中也有zxing，运行提示：
Program type already present: com.google.zxing.BarcodeFormat
Message{kind=ERROR, text=Program type already present: com.google.zxing.BarcodeFormat, sources=[Unknown source file], tool name=Optional.of(D8)}
请问我要怎么解决，谢谢

**Comment by yuzhiqiang1993** [comment]
你可以在依赖的时候使用exclude group: 'com.google.zxing‘，排除掉依赖，详情可以看一下我的一片博客,关于重复依赖冲突的解决办法：https://blog.csdn.net/yuzhiqiang_1993/article/details/78214812

**Comment by dzghxs** [comment]
好的，谢谢
