### ISSUE TITLE
发现一个对焦问题

### ISSUE THREAD

**Issue by oksimple** [yuzhiqiang1993/zxing#49]
如果镜头对准二维码开启扫描会扫描的很快，但是如果打开扫描过几秒钟再去扫二维码就会出现很模糊无法识别，我想的解决办法是关闭自动对焦，不知道作者有什么好办法嘛？

**Comment by yuzhiqiang1993** [comment]
这个我也没什么好办法，关闭聚焦的哈可能会出现一直很模糊的问题

**Comment by zhpanvip** [comment]
我也碰到这个问题，原因是不会自动对焦了。本来是要调试一下原因的，但是发现只要一插上数据线的时候就又可以自动对焦了。不太熟悉camera开发，作者可以有时间查下原因。

**Comment by zhpanvip** [comment]
最近在调bug，关于这个问题找到了解决办法。autoFocusAgainLater方法 newTask.execute()改为newTask.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR)就可以了。

**Comment by yuzhiqiang1993** [comment]
感谢反馈，有时间我会把代码加上去测试一下。再次感谢

**Comment by yuzhiqiang1993** [comment]
代码已修改
