### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by frank7023** [yuzhiqiang1993/zxing#5]
D:\MyProject\MyWelfare\app\build\intermediates\exploded-aar\com.github.yuzhiqiang1993\zxing\2.0.0\res\layout\activity_capture.xml
Error:(67) No resource identifier found for attribute 'srcCompat' in package 'com.ljzhengzai.mywelfare'
Error:(96) No resource identifier found for attribute 'srcCompat' in package 'com.ljzhengzai.mywelfare'
Error:Execution failed for task ':app:processAnzhishichangDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'E:\sdk\build-tools\22.0.1\aapt.exe'' finished with non-zero exit value 1

**Comment by yuzhiqiang1993** [comment]
你需要添加 vector-drawable依赖，例如： compile 'com.android.support:support-vector-drawable:26.0.1'
然后在你的defaultConfig配置下添加 vectorDrawables.useSupportLibrary = true
