### ISSUE TITLE
扫描识别不到二维码

### ISSUE THREAD

**Issue by zhpanvip** [yuzhiqiang1993/zxing#52]
文章的demo下载下来扫描识别正常，下载GitHub源码跑起来扫不出来。

**Comment by zhpanvip** [comment]
绝大部分情况下无法解析扫描的二维码。

**Comment by yuzhiqiang1993** [comment]
我这边测试扫描基本都能扫出来，能把您扫描的图片发一下，我试试能不能扫

**Comment by yuzhiqiang1993** [comment]
全屏扫描速度会快很多，但是有的人需求是只需要扫描框，所以这个可以自己配置
