### ISSUE TITLE
A TaskDescription's primary color should be opaque

### ISSUE THREAD

**Issue by zhpanvip** [yuzhiqiang1993/zxing#53]
在Demo中测试没有问题，但是引入项目之后就报标题的异常。版本2.1.6 /2.1.7/2.1.8都存在这个问题。

**Comment by yuzhiqiang1993** [comment]
可以看一下这篇文章，检查一下您的颜色值是否有透明度

**Comment by yuzhiqiang1993** [comment]
可以看一下这篇文章，检查一下您的颜色值是否有透明度，https://blog.csdn.net/bob1993_dev/article/details/46050655

**Comment by zhpanvip** [comment]
挺奇怪，我项目中没有主颜色用透明的，我把你代码直接作为module倒进项目就不会出现这个问题。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: yzq <notifications@github.com>
发送时间: Tuesday, August 14, 2018 4:19:33 PM
收件人: yuzhiqiang1993/zxing
抄送: zhpanvip; Author
主题: Re: [yuzhiqiang1993/zxing] A TaskDescription's primary color should be opaque (#53)


可以看一下这篇文章，检查一下您的颜色值是否有透明度，https://blog.csdn.net/bob1993_dev/article/details/46050655

―

**Comment by yuzhiqiang1993** [comment]
确实很奇怪，我这边通过依赖的方式也没有发现这个问题，但是我这边测试设备较少，可能在某些设备上有这个问题。
