### ISSUE TITLE
非全屏识别，确实识别不了。

### ISSUE THREAD

**Issue by AKJoson** [yuzhiqiang1993/zxing#57]
全屏识别速度还是蛮快的，但是非全屏识别就GG了

**Comment by yuzhiqiang1993** [comment]
你好，非全屏下我这边测试的是在扫描框内也是可以扫描的

**Comment by AKJoson** [comment]
哦哦，是因为距离的问题，一开始比较近，就识别不出来。后来才发现，要离远一点。支持，支持！
