### ISSUE TITLE
设置 ”config.setShowAlbum(false);//是否显示相册” 这个参数没效果

### ISSUE THREAD

**Issue by YunniWeng** [yuzhiqiang1993/zxing#60]

**Comment by yuzhiqiang1993** [comment]
请问是什么机型？

**Comment by YunniWeng** [comment]
> 请问是什么机型？
华为，小米，魅族，好像都没效果，就是我不想显示相册，我设置了config.setShowAlbum（false），还是显示闪光灯和相册的logo

**Comment by YunniWeng** [comment]
不好意思，我泄漏了一句            intent.putExtra(Constant.INTENT_ZXING_CONFIG, config)


> 我这边测试的是可以隐藏的，你把演示修改运行一下试试
