### ISSUE TITLE
资源文件显示不正常

### ISSUE THREAD

**Issue by xiemobiao** [yuzhiqiang1993/zxing#62]
大佬为什么集成后闪光灯图标不能正常显示,我上面默认显示的是个X，点击后图标显示正常了，再次点击关闭闪光灯又变成X的样子了

**Comment by yuzhiqiang1993** [comment]
是不是你项目中的有同名的图片资源文件跟库中的文件冲突了？

**Comment by xiemobiao** [comment]
谢谢大佬回复这么迅速，刚刚看了一下，确实是资源文件名重复了，我的项目中有个ic_close的文件名，我改一下应该就可以了。

**Comment by yuzhiqiang1993** [comment]
好的  这个是我的问题  没有考虑到这一点  不好意思  后期有时间会调整
