### ISSUE TITLE
开启闪光灯，闪退！

### ISSUE THREAD

**Issue by wjgso** [yuzhiqiang1993/zxing#63]
该加的权限也都加了，但还是会闪退，不知道为什么？

**Comment by yuzhiqiang1993** [comment]
请问有报错信息么

**Comment by wjgso** [comment]
会是我使用2.1.1版本的问题吗？ 我刚刚使用了2.1.8和2.2.0都有
Cause: duplicate entry: android/support/design/widget/CoordinatorLayout$1.class这个错误。谢谢您。

**Comment by yuzhiqiang1993** [comment]
这个好像并不是库导致的问题，你可以先试试demo报不报错

**Comment by wjgso** [comment]
闪光灯需要哪些权限？需要动态申请吗？

**Comment by yuzhiqiang1993** [comment]
文中已经说明需要哪些权限了。闪光灯：<uses-permission android:name="android.permission.FLASHLIGHT" />
无需动态申请

**Comment by wjgso** [comment]
版本2.1.1里的“打开闪光灯”的TextView，没有findView吧？？？我找了好久，后来真机测，才发现，希望您能看下。

**Comment by wjgso** [comment]
换成2.1.4版本可以很好的运行，再高的版本就会报
Cause: duplicate entry: android/support/design/widget/CoordinatorLayout$1.class这个错误，应该是我项目版本比较旧吧。

**Comment by yuzhiqiang1993** [comment]
你先试试最新的demo是不是存在问题

**Comment by yuzhiqiang1993** [comment]
长时间未回应，故关闭
