### ISSUE TITLE
使用implementation依赖的时候会有android.support包冲突的情况

### ISSUE THREAD

**Issue by mnnyang** [yuzhiqiang1993/zxing#66]
implementation ('com.github.yuzhiqiang1993:zxing:2.2.0'){
        exclude group: 'com.android.support'
    }
需要手动排除。
希望打包的时候能解决一下。

**Comment by yuzhiqiang1993** [comment]
暂时没有发现冲突的情况，如果有可以参考我的这篇博客解决：https://blog.csdn.net/yuzhiqiang_1993/article/details/78214812
