### ISSUE TITLE
findBestPreviewSizeValue=null时屏幕纵向拉伸

### ISSUE THREAD

**Issue by dreamstartLZ** [yuzhiqiang1993/zxing#68]
if (cameraResolution == null) {
      // Ensure that the camera resolution is a multiple of 8, as the screen may not be.
      cameraResolution = new Point((screenResolution.x >> 3) << 3, (screenResolution.y >> 3) << 3);
    }
应改为  cameraResolution = new Point((screenResolution.y >> 3) << 3, (screenResolution.x >> 3) << 3);

**Comment by yuzhiqiang1993** [comment]
感谢反馈，有空会测试，谢谢你
