### ISSUE TITLE
经常出现长时间聚焦不了的bug

### ISSUE THREAD

**Issue by ylcBaby** [yuzhiqiang1993/zxing#7]
大神，我发现了两个问题：
1.集成后如果手机相机像素不高的话扫描都是两秒才扫出结果，有点慢（不知道可不可以优化）
2.不管是apk还是集成后的扫码都会出现长时间聚焦不了的bug，频率还有点高。

望大神能优化，谢谢

**Comment by yuzhiqiang1993** [comment]
你好，请试试2.2.0版本
