### ISSUE TITLE
相册的二维码照片识别不了和设置config.setFullScreenScan(false)二维码就无法识别

### ISSUE THREAD

**Issue by gpitcast** [yuzhiqiang1993/zxing#70]
第一个问题使用相册识别二维码功能识别相册的二维码全部是解析失败,亲测微信可以的识别的二维码     第二个问题是当设置config.setFullScreenScan(false)时所有的二维码都不能识别    作者看到能回复下吗

**Comment by yuzhiqiang1993** [comment]
1.首先肯定是比不上微信的，但是正常的二维码还是能是别的
2.所有的二维码都无法识别暂时还没遇见过，你试试demo有没有这个问题
