### ISSUE TITLE
将module:zxinglibrary集成到自己的项目,始终识别不出来。

### ISSUE THREAD

**Issue by SophyCh** [yuzhiqiang1993/zxing#71]
你好，请教一下。下载的demo可以正常识别出二维码。将module:zxinglibrary关联到自己的项目，无论扫描多久都识别不出来，有什么方法可以解决这个问题？

**Comment by yuzhiqiang1993** [comment]
这个不应该啊，demo也有将zxinglibrary作为module关联使用的，是可以扫描的。

**Comment by SophyCh** [comment]
刚开始是，完全打不开扫描界面，闪退，没有报任何错误。后来发现是主题不匹配，更改主题后，可以显示，但是一直扫描，很久没返回结果或者在onactivityresult（…）中，resultcode=-1。




| |
陈潇宇
邮箱：cxyzyq2010@163.com
|

签名由 网易邮箱大师 定制

在2018年10月30日 11:41，yzq 写道：

这个不应该啊，demo也有将zxinglibrary作为module关联使用的，是可以扫描的。

**Comment by SophyCh** [comment]
刚开始是，完全打不开扫描界面，闪退，没有报任何错误。后来发现是CaptureActivity主题不匹配，更改主题后，可以显示，但是一直扫描，很久没返回结果或者在onActivityResult（…）中，resultCode=-1。

**Comment by yuzhiqiang1993** [comment]
有什么log信息吗

**Comment by SophyCh** [comment]
没有，都是一些普通信息。我怀疑是SDK新版本之间兼容性问题，这个module用的事SDK27，我的项目是28，现在在调低版本，保持一致试试还有什么问题。

**Comment by yuzhiqiang1993** [comment]
嗯，如果是sdk的问题，麻烦告知我一下，我更新一下

**Comment by SophyCh** [comment]
好的，谢谢支持。

**Comment by SophyCh** [comment]
终于找到问题了，我的项目存在两个问题：
1.跟zxinglibrary无关问题，在app Module中我使用了ButterKnife最新版本9.0.0-rc1，他要求使用SDK28。但是Zxinglibrary模块依赖的support-v4，support-v7,使用的是27.1.1。两者不兼容，简单的更改任何一个版本号，都会引发更多的问题。最后放弃了ButterKnife。

2.跟zxinglibrary扫描速度相关的是，ZxingConfig的配置。我项目用的之前的版本，每次都会把这个参数带过去，在更新最新的版本后，取消ZxingConfig配置，会明显快很多。

详细的原因，还没时间研究。

**Comment by SophyCh** [comment]
花了点时间终于搞明白了Gradle依赖冲突怎么解决，谢谢。
