### ISSUE TITLE
修改扫描条（自定义扫描条）

### ISSUE THREAD

**Issue by xiaodigua** [yuzhiqiang1993/zxing#72]
项目写的很好，很不错，对于实际用到项目很有作用。
但是有一个地方不大清楚，需要请教你一下，要是快速的更换扫描条应该怎么换呢？
就是替换成资源文件中的图片（scan_light.png）

**Comment by xiaodigua** [comment]
我根据你之前的代码进行了修改，很不错效果很好。
我建议是把线条的方式和配置图片的方式一起都放进去通过boolean的方式留给用户进行自我选择。
另外呢发现配置图片的有一个小细节可以完善一下。就是扫描图片的运动的起始位置：

应该是这样的，你看一下：
Rect scanRect = new Rect(frame.left, scanLineTop - scanLightHeight / 2, frame.right, scanLineTop + scanLightHeight/2);

应该要除以2，上移半个图片的高度，这样移动的过程更加的完美。

**Comment by yuzhiqiang1993** [comment]
好的，感谢建议，有时间会加上。

**Comment by androidneter** [comment]
图片线适配       
 RectF rectF = new RectF();
        rectF.top = scanLineTop - dp2px(4);
        rectF.left = frame.left;
        rectF.right = frame.right;
        rectF.bottom = scanLineTop;
        canvas.drawBitmap(lineBitmap, null, rectF, paint);

根据线粗细调节开始结束位置， rectF.top = scanLineTop - dp2px(4);
相对位置调节，  rectF.bottom = scanLineTop-***;
