### ISSUE TITLE
加密后的字符串，感觉识别率不高

### ISSUE THREAD

**Issue by cbuemc** [yuzhiqiang1993/zxing#80]
AES加密后的字符串，感觉识别率不高，扫半天扫不出来

**Comment by yuzhiqiang1993** [comment]
使用demo扫的吗？我测试的如果不是太长的字符串速度应该都还挺快的

**Comment by cbuemc** [comment]
有没办法可以提高识别率?

**Comment by yuzhiqiang1993** [comment]
实际上识别率跟是否加密没有多大关系，跟字符串长度有关系，目前来说识别率应该还是可以的。
