### ISSUE TITLE
repositories不存在，怎么整？

### ISSUE THREAD

**Issue by lanmanck** [yuzhiqiang1993/zxing#82]
我的项目没有 
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}
咋整？

**Comment by yuzhiqiang1993** [comment]
加上去呀

**Comment by lanmanck** [comment]
我的根目录没有repositories，而且我用了那么多库，都没有 repositories这个节点或者目录啥的。
另外你的apik可以扫描，项目下下来编译后运行却扫描不了，不知道啥情况？华为Hornor 4.

**Comment by yuzhiqiang1993** [comment]
1.你确定你已经成功的添加依赖了吗？
2.编译后运行扫描不了是报错了还是一直停留在扫描界面？

**Comment by lanmanck** [comment]
停留在扫描界面。
我现在把library拷贝到工程下，然后 compile 'com.github.yuzhiqiang1993:zxing:2.2.1'，不过还是报错：
Failed to resolve: com.github.yuzhiqiang1993:zxing:2.2.1。
如果拷贝到工程下，是这样做嘛？

**Comment by yuzhiqiang1993** [comment]
你直接没有用过别人的库吗？不需要拷贝的，还是文档说的，先添加maven { url 'https://jitpack.io' }到你的坟跟目录的build文件里，然后直接添加依赖就可以

**Comment by lanmanck** [comment]
![_20181206143854](https://user-images.githubusercontent.com/3500166/49566229-e8a56780-f964-11e8-8203-18e42924c089.png)
设置里看到已经添加依赖了。现在我是gradle offline，不然好慢呀。

**Comment by yuzhiqiang1993** [comment]
依赖成功后正常使用就可以了

**Comment by lanmanck** [comment]
不行呀，编译不过，要把library移除嘛？
![_20181206150814](https://user-images.githubusercontent.com/3500166/49567545-04127180-f969-11e8-873b-4a8920f374c7.png)

**Comment by yuzhiqiang1993** [comment]
你这个错误并没有看到是zxing导致的，而且你的仓库代码放错位置了，建议你看一下demo是怎么设置的

**Comment by lanmanck** [comment]
把加入的注释掉就可以编译了。要怎么放呢？
![_20181206151500](https://user-images.githubusercontent.com/3500166/49567854-ebef2200-f969-11e8-8e65-c4898e69dc91.png)

**Comment by lanmanck** [comment]
反应很慢，要扫很久才可能扫到。但是你的apk就不会。
另外你这种集成方式能改下嘛？比如我要改layout，增加多语言。这样从网络下载的话，没法变。还是导入源码到工程最好。

**Comment by yuzhiqiang1993** [comment]
你可以直接下载源码作为module导入使用

**Comment by yuzhiqiang1993** [comment]
我这边测试的速度还可以，你试试其他的库吧

**Comment by lanmanck** [comment]
好像都是一个鸟样，试了4、5个，包括4000多个星的，也慢的不行。但是一打包成apk单独安装就行了，这什么情况。
