### ISSUE TITLE
当设置不是全屏扫描，离二维码很近基本识别不出

### ISSUE THREAD

**Issue by langren0610** [yuzhiqiang1993/zxing#83]
当设置不是全屏扫描，将二维码完全显示在扫描框内，基本识别不出。需要离二维码很远才能识别出来。

**Comment by yuzhiqiang1993** [comment]
我这边测试的离得近一些也是可以是别的啊，而且速度还是挺快的。

**Comment by longkiGit** [comment]
我这边几十人测试都是，离得近不行。 。

**Comment by langren0610** [comment]
>           我这边几十人测试都是，离得近不行。 。

出现这个问题的原因大概是：设置不是全屏时，因为没有了actionbar，解析的二维码高度往上偏移了一噶actionbar的高度，导致近的时候解析不出来，远的时候二维码小完全在框内，可以解析。这个需要修改代码，在设置不是全屏并且没有actionbar的时候，需要将解析的高度往下偏移一个action的距离：在CameraManager类中的方法public PlanarYUVLuminanceSource buildLuminanceSource(byte[] data,
                                                         int width, int height)，修改：if (config.isFullScreenScan()) {
            return new PlanarYUVLuminanceSource(data, width, height, 0,
                    0, width, height, false);
        } else {
            int actionbarHeight = context.getResources().getDimensionPixelSize(R.dimen.actionbar_height);
            return new PlanarYUVLuminanceSource(data, width, height, rect.left,
                    rect.top + actionbarHeight, rect.width(), rect.height(), false);
        }。希望对你有帮助。

**Comment by yuzhiqiang1993** [comment]
非常感反馈，已调整，测试后发布新版本

**Comment by yuzhiqiang1993** [comment]
再次感谢，已发布2.2.5版本
