### ISSUE TITLE
CaptureActivity、startActivityForResult都是红色的

### ISSUE THREAD

**Issue by a18538328225** [yuzhiqiang1993/zxing#86]
项目启动不起来CaptureActivity、startActivityForResult都是红色的，

**Comment by niewenlong123** [comment]
你配置有问题，照着demo进行配置，，，看看报什么错

**Comment by a18538328225** [comment]
REQUEST_CODE_SCAN找不到这个变量，，这个变量是从哪里来的啊？需要怎么引入

**Comment by a18538328225** [comment]
Intent intent = new Intent(MainActivity.this, CaptureActivity.class); 我只能放在MainActivity.java里才能用
放到其他类里面 就报错 ：不是封闭类: MainActivity？

**Comment by a18538328225** [comment]
终于搞定了，感谢大神指点迷津
