### ISSUE TITLE
魅族的5.0 系统 扫描条始终在顶部。代码是执行的 但是 就是没有绘制 扫描条

### ISSUE THREAD

**Issue by caiyc0818** [yuzhiqiang1993/zxing#89]
private void initAnimator() {

        if (valueAnimator == null) {
            valueAnimator = ValueAnimator.ofInt(frame.top, frame.bottom);
            valueAnimator.setDuration(3000);
            valueAnimator.setInterpolator(new DecelerateInterpolator());
            valueAnimator.setRepeatMode(ValueAnimator.RESTART);
            valueAnimator.setRepeatCount(ValueAnimator.INFINITE);
            valueAnimator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
                @Override
                public void onAnimationUpdate(ValueAnimator animation) {

                    scanLineTop = (int) animation.getAnimatedValue();
                    invalidate();

                }
            });

            valueAnimator.start();
        }

    }

始终 距离不变

**Comment by yuzhiqiang1993** [comment]
打印下top和bottom的值看一下是否有问题

**Comment by caiyc0818** [comment]
一直都没变化

**Comment by yuzhiqiang1993** [comment]
top和bottom的值分别是多少，scanLineTop的值没有变化吗？

**Comment by yuzhiqiang1993** [comment]
长时间未回复，故关闭
