### ISSUE TITLE
这是啥错啊？？？？

### ISSUE THREAD

**Issue by liguangze** [yuzhiqiang1993/zxing#9]
Error:(6, 0) Gradle DSL method not found: 'google()'
Possible causes:<ul><li>The project 'zxing-master' may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0).
<a href="fixGradleElements">Upgrade plugin to version 2.3.0 and sync project</a></li><li>The project 'zxing-master' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>

**Comment by liguangze** [comment]
已解决，谢谢开源

**Comment by liguangze** [comment]
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support:design:26.1.0'
    implementation 'com.android.support:support-vector-drawable:26.1.0'
    implementation 'com.yanzhenjie:permission:1.1.0'
    implementation project(':zxinglibrary')
}
implementation 为什么用这个构建啊  不是都是compile  项目下载下来总有错呢

**Comment by liguangze** [comment]
E:\studioWorkspace\zxing-master\app\src\main\java\com\yzq\zxing\MainActivity.java
Error:(20, 24) 错误: 程序包com.google.zxing不存在
Error:(24, 33) 错误: 程序包com.yzq.zxinglibrary.bean不存在
Error:(25, 35) 错误: 程序包com.yzq.zxinglibrary.common不存在
Error:(26, 35) 错误: 程序包com.yzq.zxinglibrary.encode不存在
Error:(88, 33) 错误: 找不到符号
符号: 类 ZxingConfig
Error:(88, 58) 错误: 找不到符号
符号: 类 ZxingConfig
Error:(91, 49) 错误: 找不到符号
符号: 变量 Constant


studio改成了3.0以下的方式，这些都找不到呢，什么原因

**Comment by yuzhiqiang1993** [comment]
应该是你的依赖环境有问题，重新依赖下试试

**Comment by liguangze** [comment]
不是我依赖的啊，是我运行你的项目，但是编译能通过，但是一运行就报错

**Comment by yuzhiqiang1993** [comment]
根据你上面提供的信息来看，可能是你本地的环境问题导致编译没有通过，demo是可以运行的，你再编译一下运行看看，如果还是不行的话，我加一下你QQ看看是什么问题导致的

**Comment by liguangze** [comment]
好的，谢谢  429475006
