### ISSUE TITLE
内存泄露怎么处理？谢谢

### ISSUE THREAD

**Issue by liangdong11** [yuzhiqiang1993/zxing#92]

**Comment by yuzhiqiang1993** [comment]
请问是哪个地方的内存泄漏呢？

**Comment by liangdong11** [comment]
![21545806635_ pic](https://user-images.githubusercontent.com/15180136/50435572-ca57d980-091c-11e9-96a9-c23352f64a21.jpg)

**Comment by yuzhiqiang1993** [comment]
好的，有时间会排查

**Comment by liangdong11** [comment]
嗯嗯。谢谢您可以及时更新
