### ISSUE TITLE
怎么去掉扫描界面的actionbar

### ISSUE THREAD

**Issue by zhenCyyl** [yuzhiqiang1993/zxing#93]
![qq 20190103145509](https://user-images.githubusercontent.com/35480633/50626157-9bb6b000-0f67-11e9-8182-bb5990cc0d20.png)

**Comment by yuzhiqiang1993** [comment]
这个是根据你项目的主题配置的，将你自己项目的主题修改为NoTitleBar之类的即可

**Comment by yuzhiqiang1993** [comment]
demo中的主题是  `Theme.AppCompat.Light.NoActionBar`
