### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by UsernameZcl** [yuzhiqiang1993/zxing#95]
扫描的时候，能否连续扫描，这个功能也是一个比较常见你的功能

**Comment by yuzhiqiang1993** [comment]
你好，能描述一下连续扫描使用场景吗？

**Comment by UsernameZcl** [comment]
其实就是类似于超市扫描枪一样的，连续扫描。说白一点就是点击扫描之后，扫描到条码之后，界面没有关闭，还能继续扫描，用户点击返回箭头的时候，把扫描到的数据返回。我修改了你的代码  
在  handleDecode （）；方法中加入ontinuePreview()的方法，就可以进行连续扫描，我也是根据自己项目中的需求来做的，其他需求还要视情况而定。这个项目扫描挺快的，
  /**
     * 使Zxing能够继续扫描
     */
    public void continuePreview() {
        if (handler != null) {
            handler.restartPreviewAndDecode();
        }
    }

**Comment by yuzhiqiang1993** [comment]
像这种需求暂时只能先修改源码实现啦，目前还是类似于微信那种单次扫描用的较多，同时感谢你的建议，后期如果需求多的话会考虑加上去
