### ISSUE TITLE
CameraManager的327行 自定义情况下的topOffset也应该除以5才一致吧

### ISSUE THREAD

**Issue by GALAXYDUKE** [yuzhiqiang1993/zxing#97]
同Title

**Comment by yuzhiqiang1993** [comment]
为什么要除以5呢？肯定是除以2啊

**Comment by GALAXYDUKE** [comment]
因为我看默认的处理，258行的topOffset都是除以5的，所以显示在界面偏上的位置；但是，我现在需要自定义宽度和高度，所以调用了setManualFramingRect这个方法重新设置大小，结果由于327行这只除以了2，导致整个区域显示在界面的偏下的地方了

**Comment by yuzhiqiang1993** [comment]
哦，对的，我疏忽了，感谢反馈。

**Comment by yuzhiqiang1993** [comment]
有界面自定义需求的，暂时还是自行修改源码实现吧，每个人需求不一样，没有一个统一的标准，我这边也只能暂时给一个相对通用的界面了。
