### ISSUE TITLE
扫码速度不错，可惜就是耦合度比较高

### ISSUE THREAD

**Issue by NerdAnonymous** [yuzhiqiang1993/zxing#98]

**Comment by yuzhiqiang1993** [comment]
目前来讲普通的扫描二维码应该是满足了，兄台有好的建议欢迎提出来

**Comment by woxiangxin7779** [comment]
这 耦合度 我真的日了

**Comment by yuzhiqiang1993** [comment]
不知道你所说的耦合度高是在哪个地方，目前来讲十几行代码基本就能完成二维码扫描了，且该库与你自己的项目之间关联也并不是很多，无非就是一个onActivityResult。
这个库也是基于zxing封装的，目的就是为了让使用的人相对方便一些，如果有好的建议，欢迎提出来，我这边也好进行优化

**Comment by yuzhiqiang1993** [comment]
依赖之后不能用？不会吧。按照文档走应该是没问题的。
至于你所说的耦合度高，我认为只要这个扫一扫模块跟你的项目之间的关联不多就可以，至于项目里面的代码是基于Zxing代码修改的，这个你可能需要去Zxing那边去提出这个问题了。
